# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 588)
        MainWindow.setStyleSheet("QCheckBox::checked{color: rgb(255, 0, 0);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QRadioButton:checked{color:red;}\n"
"QListWidget::item:selected{color:red;}\n"
"QTabBar::tab{background-color:rbg(255,255,255,0);} QTabBar::tab:selected{color:red;background-color:rbg(255,200,255);} ")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sh = QtWidgets.QRadioButton(self.centralwidget)
        self.sh.setObjectName("sh")
        self.horizontalLayout_3.addWidget(self.sh)
        self.sz = QtWidgets.QRadioButton(self.centralwidget)
        self.sz.setObjectName("sz")
        self.horizontalLayout_3.addWidget(self.sz)
        self.sh300 = QtWidgets.QRadioButton(self.centralwidget)
        self.sh300.setObjectName("sh300")
        self.horizontalLayout_3.addWidget(self.sh300)
        self.zz500 = QtWidgets.QRadioButton(self.centralwidget)
        self.zz500.setObjectName("zz500")
        self.horizontalLayout_3.addWidget(self.zz500)
        self.cyb = QtWidgets.QRadioButton(self.centralwidget)
        self.cyb.setObjectName("cyb")
        self.horizontalLayout_3.addWidget(self.cyb)
        self.zx = QtWidgets.QRadioButton(self.centralwidget)
        self.zx.setObjectName("zx")
        self.horizontalLayout_3.addWidget(self.zx)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stock_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_list.sizePolicy().hasHeightForWidth())
        self.stock_list.setSizePolicy(sizePolicy)
        self.stock_list.setObjectName("stock_list")
        self.horizontalLayout_2.addWidget(self.stock_list)
        self.main_show = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_show.sizePolicy().hasHeightForWidth())
        self.main_show.setSizePolicy(sizePolicy)
        self.main_show.setStyleSheet("")
        self.main_show.setObjectName("main_show")
        self.timebar = DockArea()

        self.timebar_d1 = Dock('dock1')
        self.timebar_d1.hideTitleBar()
        self.timebar.addDock(self.timebar_d1, 'top', )
        self.timebar_d2 = Dock('dock2')
        self.timebar_d2.hideTitleBar()
        self.timebar.addDock(self.timebar_d2, 'bottom')

        self.timebar.setObjectName("timebar")
        self.main_show.addTab(self.timebar, "")
        self.kline = DockArea()

        self.kline_d1 = Dock('dock1')
        self.kline_d1.hideTitleBar()
        self.kline.addDock(self.kline_d1, 'top', )
        self.kline_d2 = Dock('dock2')
        self.kline_d2.hideTitleBar()
        self.kline.addDock(self.kline_d2, 'bottom')

        self.kline.setObjectName("kline")
        self.main_show.addTab(self.kline, "")
        self.infor = QtWidgets.QWidget()
        self.infor.setObjectName("infor")
        self.main_show.addTab(self.infor, "")
        self.horizontalLayout_2.addWidget(self.main_show)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buy_list = QtWidgets.QListWidget(self.centralwidget)
        self.buy_list.setObjectName("buy_list")
        self.gridLayout.addWidget(self.buy_list, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sell_list = QtWidgets.QListWidget(self.centralwidget)
        self.sell_list.setObjectName("sell_list")
        self.gridLayout.addWidget(self.sell_list, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.news = QtWidgets.QLabel(self.centralwidget)
        self.news.setEnabled(True)
        self.news.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.news.setObjectName("news")
        self.horizontalLayout.addWidget(self.news)
        self.stock_code = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_code.sizePolicy().hasHeightForWidth())
        self.stock_code.setSizePolicy(sizePolicy)
        self.stock_code.setMaximumSize(QtCore.QSize(70, 16777215))
        self.stock_code.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 87 14pt \"Arial\";")
        self.stock_code.setMaxLength(6)
        self.stock_code.setObjectName("stock_code")
        self.horizontalLayout.addWidget(self.stock_code)
        self.time_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_lcd.sizePolicy().hasHeightForWidth())
        self.time_lcd.setSizePolicy(sizePolicy)
        self.time_lcd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.time_lcd.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\";")
        self.time_lcd.setDigitCount(10)
        self.time_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.time_lcd.setProperty("value", 12345678.0)
        self.time_lcd.setObjectName("time_lcd")
        self.horizontalLayout.addWidget(self.time_lcd)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_show.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sh.setText(_translate("MainWindow", "沪A"))
        self.sz.setText(_translate("MainWindow", "深A"))
        self.sh300.setText(_translate("MainWindow", "沪深300"))
        self.zz500.setText(_translate("MainWindow", "中证500"))
        self.cyb.setText(_translate("MainWindow", "创业板"))
        self.zx.setText(_translate("MainWindow", "自选"))
        self.main_show.setTabText(self.main_show.indexOf(self.timebar), _translate("MainWindow", "分时"))
        self.main_show.setTabText(self.main_show.indexOf(self.kline), _translate("MainWindow", "K线"))
        self.main_show.setTabText(self.main_show.indexOf(self.infor), _translate("MainWindow", "个股资料"))
        self.label_2.setText(_translate("MainWindow", "买\n"
"盘"))
        self.label.setText(_translate("MainWindow", "卖\n"
"盘"))
        self.news.setText(_translate("MainWindow", "news"))
        self.stock_code.setText(_translate("MainWindow", "000001"))
from pyqtgraph.dockarea import DockArea, Dock
